version: '2'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.12.1
    hostname: ganache
    ports:
      - 8545:8545

  app:
    build: .
    depends_on:
      - ganache
    hostname: app
    ports:
    - 8080:3000
