const fs = require('fs');
const HDWalletProvider = require("@truffle/hdwallet-provider");

// 'seed' defined in this file was generated by ganache. It's use in the docker-compose comfig
//    so that the same addresses are generated whenever ganache restarts
// `projectId` was generated when creating a new project in infura
const secrets = JSON.parse(
    fs.readFileSync("/app/.secrets").toString().trim()
);

module.exports = {
  networks: {
    development: {
     host: "ganache",
     port: 8545,
     network_id: "*",
    },
    ropsten : {
      network_id: 3,
      provider: () =>
          new HDWalletProvider({
              mnemonic: secrets.seed,
              providerOrUrl: `wss://ropsten.infura.io/ws/v3/${secrets.projectId}`,
          }),
    }
  },

  mocha: {
    reporter: 'eth-gas-reporter',
    reporterOptions: {
        currency: 'USD'
    }
  },

  compilers: {
    solc: {
      version: "0.7.5",
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    },
  },
};
